# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b882d29f5416861afca406eb0a63d7a77167bf7e16f60868b67ff250ae4b4eb082e94873ac600b5c8aa178c5582f9dbac5cf11278ed530f64f60406a77d227c4

test:
  secret_key_base: 80075c9b490ef8faa641818da84a1b3656e2c5fa1bb1a94f3c2fb900fa805fa8e844e853b134d6bd66862f4ffe5a01aff6dc3f9c5ef6b3575a48846f08b7626c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
